#Broadlink RM Pro
- platform: broadlink
  host: 172.20.2.134
  mac: !secret rmpro_mac
  timeout: 15
  friendly_name: 'Broadlink'
  switches:
    !include_dir_merge_named broadlink_switches
- platform: xiaomi_miio
  name: Powerstrip in Living Room
  host: 172.20.2.67
  token: !secret powerstrip_lr_token
- platform: xiaomi_miio
  name: Powerstrip in Dining Room
  host: 172.20.2.68
  token: !secret powerstrip_dr_token

